-- WASEL authorization foundation.
-- Run this file in Supabase SQL Editor after Supabase Auth is configured.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null unique,
  requested_account_type text not null default 'passenger'
    check (requested_account_type in ('passenger', 'driver', 'company')),
  role text not null default 'passenger'
    check (role in ('passenger', 'driver', 'company', 'supervisor', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label_ar text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_permissions (
  user_id uuid not null references public.profiles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  granted_by uuid references public.profiles(id) on delete set null,
  granted_at timestamptz not null default now(),
  primary key (user_id, permission_id)
);

alter table public.profiles enable row level security;
alter table public.permissions enable row level security;
alter table public.user_permissions enable row level security;

insert into public.permissions (code, label_ar)
values
  ('manage_users', 'إدارة المستخدمين'),
  ('manage_drivers', 'إدارة السائقين'),
  ('manage_companies', 'إدارة شركات النقل'),
  ('manage_ads', 'إدارة الإعلانات'),
  ('monitor_rides', 'مراقبة الرحلات'),
  ('manage_settings', 'إدارة إعدادات النظام'),
  ('view_reports', 'عرض التقارير'),
  ('manage_permissions', 'إدارة الصلاحيات')
on conflict (code) do nothing;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    full_name,
    phone,
    requested_account_type
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(
      new.raw_user_meta_data ->> 'requested_account_type',
      'passenger'
    )
  )
  on conflict (id) do update
  set
    full_name = excluded.full_name,
    phone = excluded.phone,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and is_active = true
  );
$$;

create or replace function public.has_permission(permission_code text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_admin()
    or exists (
      select 1
      from public.profiles p
      join public.user_permissions up on up.user_id = p.id
      join public.permissions pm on pm.id = up.permission_id
      where p.id = auth.uid()
        and p.is_active = true
        and p.role = 'supervisor'
        and pm.code = permission_code
    );
$$;

create or replace function public.set_requested_account_type(account_type text)
returns boolean
language plpgsql
security definer
set search_path = public
as $
begin
  if account_type not in ('passenger', 'driver', 'company') then
    return false;
  end if;

  update public.profiles
  set requested_account_type = account_type,
      updated_at = now()
  where id = auth.uid();

  update auth.users
  set raw_user_meta_data =
        coalesce(raw_user_meta_data, '{}'::jsonb)
        || jsonb_build_object(
          'requested_account_type',
          account_type
        )
  where id = auth.uid();

  return found;
end;
$;

grant execute on function public.set_requested_account_type(text)
to authenticated;

create or replace function public.phone_account_exists(normalized_phone text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where phone = normalized_phone
      and is_active = true
  );
$$;

revoke all on function public.phone_account_exists(text) from public;
grant execute on function public.phone_account_exists(text) to anon, authenticated;

create policy "Users can read own profile"
on public.profiles
for select
to authenticated
using (id = auth.uid());

create policy "Admins can read all profiles"
on public.profiles
for select
to authenticated
using (public.is_admin());

create policy "Admins can update profiles"
on public.profiles
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Supervisors can read permitted profiles"
on public.profiles
for select
to authenticated
using (
  public.has_permission('manage_users')
  or public.has_permission('manage_drivers')
  or public.has_permission('manage_companies')
);

create policy "Authenticated users can read permissions"
on public.permissions
for select
to authenticated
using (true);

create policy "Admins can manage permissions"
on public.permissions
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Users can read own granted permissions"
on public.user_permissions
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "Admins can manage user permissions"
on public.user_permissions
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
