      'إرسال مباشر للطرد': 'Direct parcel delivery',
      'السعر التقديري': 'Estimated price',
      'جنيه': 'SDG',
      'يرجى إكمال بيانات المرسل والمستلم': 'Please complete the sender and recipient details',
      'تم إنشاء طلب الطرد': 'Parcel request created',
      'احتفظ برقم التتبع لمتابعة طردك': 'Keep the tracking number to track your parcel',
      'رقم التتبع': 'Tracking number',
      'متابعة وتتبع الطرد': 'Continue and track parcel',
      'من': 'From',
      'إلى': 'To',
      'المركبات المتاحة لهذا المسار': 'Vehicles available for this route',
      'رحلة قائمة': 'Available trip',
      'اختيار الرحلة': 'Choose trip',
      'لا توجد رحلة قائمة بهذا النوع حالياً': 'No available trip of this type right now',
      'يمكنك العودة واختيار نوع مركبة آخر أو المحاولة لاحقاً.': 'You can go back and choose another vehicle type or try again later.',
      'تاريخ السفر': 'Travel date',
      'عدد المسافرين': 'Passengers',
      'اختر عدد المقاعد': 'Choose number of seats',
      'اختر المسار أولاً. بعد ذلك تظهر أنواع المركبات المتاحة، ثم الرحلات القائمة والمقاعد المتبقية. لا يتم عرض شركات النقل للمسافر؛ إدارة واصل تتولى تنسيق الناقل عند الحاجة.': 'Choose the route first. Then available vehicle types, trips, and remaining seats will appear. Transport companies are not shown to passengers; WASEL coordinates the carrier when needed.',